---
title: "Supplementary Fig. 1"
author: "Lauren Zamora"
format: html
editor: visual
---

## Supplementary Figure 1

This figure shows the average frequency of CALIPSO dust aerosol layer occurrences and mean MERRA-2 and FLEXPART dust concentrations at different altitudes, along with the Pierson weighted R-squared for bins with \> 40 samples, weighted by the area of the different geographic bins. The size of the data is related to the geographic bin area. The dashed blue line is a qualitative marker between the lowest and highest observed dust layer frequencies.

## Running Code

For **Supplementary Figure 1** first load the following libraries:

```{r}
library(data.table)
library(geosphere)
```

This is a calculation of the Pierson weighted R-squared of mean dust vs. mean CALIPSO dust overlap across the different geographic bins, weighted by the area of the bins. Data are from Zamora et al., 2022. The ftop, fbase and ptop, pbase are the bottom and top altitudes (in km) of the layer in which the FLEXPART/MERRA-2 aerosol data are taken from. These vary because in MERRA-2 the data were based on pressure levels, and in FLEXPART we had to get values relative to sea level, not ground level.
